@startuml deployment
!include ../../C4-PlantUML/C4_Deployment.puml

LAYOUT_WITH_LEGEND()

Deployment_Node(plc, "Cloud", "The cloud provider boundary"){
    Deployment_Node(id, "Azure Entra ID", "Azure Authentication"){
        Container(entra, "Azure Entra ID", "Azure Entra ID", "Manages the authentication and authorization of customers.")
    }
    Deployment_Node(cn, "Content Delivery Network", "Azure CDN"){
        Container(cdn, "CDN", "Azure CDN", "Delivers all static content to the customer's web browser.")
    }
    Deployment_Node(ln, "Load Balancer", "Azure Load Balancer"){
        Container(load, "Load Balancer", "Azure Load Balancer", "Distributes incoming HTTP requests across multiple instances of the API.")
    }
    Deployment_Node(sn, "Azure Service Fabric", "Azure Service Fabric"){
        Container(svc, "Azure Service Fabric", "Azure Service Fabric", "Hosts the API and background running tasks.")
    }
    Deployment_Node(db1, "Azure MySQL", "Azure MySQL"){
        Container(mysql, "Azure MySQL", "Azure MySQL", "Stores all data of the application except GPS tracking data.")
    }
    Deployment_Node(db2, "Azure MongoDB", "Azure MongoDB"){
        Container(mongo, "Azure MongoDB", "Azure MongoDB", "Stores GPS tracking data.")
    }
}

Deployment_Node(mob, "Customer's mobile device", "Apple IOS or Android"){
    Container(mobile, "Mobile App", "React Native", "Provides the running tracking functionality via their mobile device.")
}

Deployment_Node(comp, "Customer's computer", "MS Windows / Apple macOS / Linux"){
    Deployment_Node(browser, "Web Browser", "Google Chrome, Mozilla Firefox, Edge"){
        Container(spa, "SPA", "react/HTML/CSS", "Provides all of the running data dashboard and account functionality to customers via their web browser.")
    }
}

Rel(mobile, entra, "Authenticates", "json/HTTPS")
Rel(browser, entra, "Authenticates", "json/HTTPS")
Rel(browser, cdn, "Authenticates", "json/HTTPS")
Rel(mobile, load, "Makes API calls to", "json/HTTPS")
Rel(spa, load, "Serves", "json/HTTPS")
Rel(mobile, load, "Delivers to the customer's web browser")
Rel(load, svc, "The services for the running application")
Rel(svc, mysql, "Running data for dashboard", "json/HTTPS")
Rel(svc, mongo, "Write intensive data", "json/HTTPS")
Rel(mysql, mongo, "Reads historical tracking data", "JDBC")

@enduml