@startuml deployment
!include ../../C4-PlantUML/C4_Deployment.puml

LAYOUT_WITH_LEGEND()

Deployment_Node(plc, "Cloud", "The cloud provider boundary"){
    Deployment_Node(dn, "running-vm1", "16GB Ram - 4Core - Ubuntu 18.04 LTS"){
        Deployment_Node(apache2, "Apache Tomcat", "Apache Tomcat 8.x"){
            Container(web, "Web Application", "Java and Spring MVC", "Provides static content and SPA to customer web browser.")
        }
    }
    Deployment_Node(lambda, "API", "Serverless on Lambdas"){
        Container(api, "API Application", "Java Spring Service", "Provides all running app functionality to both Mobile and Web App via a JSON/HTTPS API.")
    }
    Deployment_Node(db01, "running-vm2", "200GB Ram - 32Core - Ubuntu 18.04 LTS"){
        Deployment_Node(mysql, "MySQL", "MySQL 5.7"){
            ContainerDb(db1, "Database", "Relational Database Schema", "Stores all data of the application except GPS tracking data.")
            ContainerDb(db2, "Database", "NoSQL Database", "Stores GPS tracking data")
        }
    }
}

Deployment_Node(mob, "Customer's mobile device", "Apple IOS or Android"){
    Container(mobile, "Mobile App", "React Native", "Provides the running tracking functionality via their mobile device.")
}

Deployment_Node(comp, "Customer's computer", "MS Windows / Apple macOS / Linux"){
    Deployment_Node(browser, "Web Browser", "Google Chrome, Mozilla Firefox, Edge"){
        Container(spa, "SPA", "react/HTML/CSS", "Provides all of the running data dashboard and account functionality to customers via their web browser.")
    }
}

Rel(mobile, api, "Makes API calls to", "json/HTTPS")
Rel(spa, api, "Delivers to the customer's web browser")
Rel(browser, web, "Serves", "json/HTTPS")
Rel(web, db1, "Reads Authentication and plans", "json/HTTPS")
Rel(api, db1, "Reads all data except", "json/HTTPS")
Rel(api, db2, "Only writes specific GPS tracking data", "JDBC")

@enduml