@startuml deployment
!include ../../C4-PlantUML/C4_Deployment.puml

LAYOUT_WITH_LEGEND()

Deployment_Node(plc, "Cloud", "The cloud provider boundary"){
    Deployment_Node(dn, "running-vm1", "200GB Ram - 32Core - Ubuntu 18.04 LTS"){
        Deployment_Node(apache2, "Apache Tomcat", "Apache Tomcat 8.x"){
            Container(web, "Web Application", "Java and Spring MVC", "Provides static content and SPA to customer web browser.")
            Container(api, "API Application", "Java and Spring MVC", "Provides all running app functionality to both Mobile and Web App via a JSON/HTTPS API.")
        }        
    }
    Deployment_Node(db01, "running-vm2", "200GB Ram - 32Core - Ubuntu 18.04 LTS"){
        Deployment_Node(mysql, "MySQL", "MySQL 5.7"){
            ContainerDb(db, "Database", "Relational Database Schema", "Stores all data from App: user account information, credentials, running tracking data")
        }
    }
}

Deployment_Node(mob, "Customer's mobile device", "Apple IOS or Android"){
    Container(mobile, "Mobile App", "React Native", "Provides the running tracking functionality via their mobile device.")
}

Deployment_Node(comp, "Customer's computer", "MS Windows / Apple macOS / Linux"){
    Deployment_Node(browser, "Web Browser", "Google Chrome, Mozilla Firefox, Edge"){
        Container(spa, "SPA", "react/HTML/CSS", "Provides all of the running data dashboard and account functionality to customers via their web browser.")
    }
}

Rel(mobile, api, "Makes API calls to", "json/HTTPS")
Rel(spa, api, "Delivers to the customer's web browser")
Rel(browser, web, "Serves", "json/HTTPS")
Rel(api, db, "Reads from and writes to", "JDBC")

@enduml